---
- name: Ensure the secret that stores the Quay connection parameters exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: quay-connection-secret
        namespace: "{{ namespace }}"
      stringData:
        host: https://quay.quay.svc.cluster.local
        validateCerts: "false"
