# This rule is not used by the project quay-api-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to quay.herve4m.github.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: quay-api-operator
    app.kubernetes.io/managed-by: kustomize
  name: organizationimmutability-viewer-role
rules:
- apiGroups:
  - quay.herve4m.github.io
  resources:
  - organizationimmutabilities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - quay.herve4m.github.io
  resources:
  - organizationimmutabilities/status
  verbs:
  - get
