# permissions for end users to view tags.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tag-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: quay-api-operator
    app.kubernetes.io/part-of: quay-api-operator
    app.kubernetes.io/managed-by: kustomize
  name: tag-viewer-role
rules:
- apiGroups:
  - quay.herve4m.github.io
  resources:
  - tags
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - quay.herve4m.github.io
  resources:
  - tags/status
  verbs:
  - get
