# permissions for end users to edit users.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: quay-api-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-editor-role
rules:
- apiGroups:
  - quay.herve4m.github.io
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quay.herve4m.github.io
  resources:
  - users/status
  verbs:
  - get
