---
apiVersion: quay.herve4m.github.io/v1alpha1
kind: RepositoryImmutability
metadata:
  name: repositoryimmutability-sample
spec:
  # Connection parameters in a Secret resource
  connSecretRef:
    name: quay-credentials-secret
    # By default, the operator looks for the secret in the same namespace as
    # the repositoryimmutability resource, but you can specify a different namespace.
    # namespace: mynamespace

  # Whether to preserve the corresponding Quay object when you
  # delete the RepositoryImmutability resource.
  preserveInQuayOnDeletion: false

  repository: production/ubi9
  tagPattern: "release-.*"
  behavior: matching_immutable
