---
apiVersion: quay.herve4m.github.io/v1alpha1
kind: Application
metadata:
  name: application-sample
spec:
  # Connection parameters in a Secret resource
  connSecretRef:
    name: quay-temp-credentials-secret
    # By default, the operator looks for the secret in the same namespace as
    # the application resource, but you can specify a different namespace.
    # namespace: mynamespace

  # Whether to preserve the corresponding Quay object when you
  # delete the resource.
  preserveInQuayOnDeletion: false

  name: extapp
  organization: production
  description: External application
  applicationUri: http://applicationuri.example.com
  avatarEmail: avatarextapp@example.com
  redirectUri: http://redirecturi.example.com

  # The Secret resource is created or updated, and stores the returned data.
  # You can use that secret with an ApiToken custom resource to create an
  # OAuth access token.
  retSecretRef:
    name: application-secret
    # By default, the operator stores the secret in the same namespace as the
    # application resource, but you can specify a different namespace.
    # namespace: mynamespace
