---
apiVersion: quay.herve4m.github.io/v1alpha1
kind: OrganizationMirror
metadata:
  name: organizationmirror-sample
spec:
  # Connection parameters in a Secret resource
  connSecretRef:
    name: quay-credentials-secret
    # By default, the operator looks for the secret in the same namespace as
    # the organizationmirror resource, but you can specify a different namespace.
    # namespace: mynamespace

  # Whether to preserve the corresponding Quay object when you
  # delete the OrganizationMirror resource.
  preserveInQuayOnDeletion: false

  organization: productionmirror
  externalRegistryType: quay
  externalRegistryUrl: https://quay.io
  externalNamespace: projectquay
  robotUsername: productionmirror+syncrobot
  visibility: public
  repositoryFilters:
    - quay
    - clair
    - redis
  syncInterval: 2d
  syncStartDate: "2026-04-27T13:00:00Z"
  isEnabled: true
