---
apiVersion: quay.herve4m.github.io/v1alpha1
kind: RepositoryPrune
metadata:
  name: repositoryprune-sample
spec:
  # Connection parameters in a Secret resource
  connSecretRef:
    name: quay-credentials-secret
    # By default, the operator looks for the secret in the same namespace as
    # the repositoryprune resource, but you can specify a different namespace.
    # namespace: mynamespace

  # Whether to preserve the corresponding Quay object when you
  # delete the RepositoryPrune resource.
  preserveInQuayOnDeletion: false

  repository: production/smallimage
  method: tags
  value: 5
  tag_pattern: nightly
