---
- name: Ensure the Quay namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: quay
    state: '{{ state }}'

- name: Ensure the Quay resources are running
  kubernetes.core.k8s:
    namespace: quay
    state: '{{ state }}'
    wait: true
    wait_timeout: 300
    definition: "{{ item | ansible.builtin.from_yaml_all }}"
  with_file:
    - ../../scripts/Quay-in-OpenShift/postgresql.yaml
    - ../../scripts/Quay-in-OpenShift/redis.yaml
    - ../../scripts/Quay-in-OpenShift/fake-clair.yaml
    - ../../scripts/Quay-in-OpenShift/quay.yaml
