---
- name: Ensure the organizationprune resource exists
  block:
    - name: Ensure the secret resource that stores the Quay parameters exists
      ansible.builtin.fail:
        msg: "connSecretRef: {{ conn_secret_ref['name'] }}: secret not found"
      when:
        - not secret_found

    - name: Ensure the organizationprune resource exists in Quay
      infra.quay_configuration.quay_organization_prune:
        quay_host: "{{ quay_host | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
        quay_token: "{{ quay_token | default(omit, true) }}"
        quay_username: "{{ omit if quay_token is defined and quay_token | length > 0 else quay_username | default(omit) }}"
        quay_password: "{{ omit if quay_token is defined and quay_token | length > 0 else quay_password | default(omit) }}"
        append: "{{ append | default(omit) }}"
        method: "{{ method | default(omit) }}"
        namespace: "{{ namespace | default(omit) }}"
        tag_pattern: "{{ tag_pattern | default(omit) }}"
        tag_pattern_matches: "{{ tag_pattern_matches | default(omit) }}"
        value: "{{ value | default(omit) }}"
      register: ret

    - name: Ensure the existInQuay flag is set in the resource status
      operator_sdk.util.k8s_status:
        api_version: quay.herve4m.github.io/v1alpha1
        kind: OrganizationPrune
        name: "{{ ansible_operator_meta['name'] }}"
        namespace: "{{ ansible_operator_meta['namespace'] }}"
        status:
          existInQuay: true

    - name: Ensure the resulting data is saved in a secret
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: "{{ ret_secret_ref['name'] }}"
            namespace: "{{ ret_secret_ref['namespace'] | default(ansible_operator_meta['namespace']) }}"
          data:
            id: "{{ ret['id'] | default('', true) | ansible.builtin.b64encode }}"
      when:
        - ret_secret_ref is defined
        - "'name' in ret_secret_ref"
        - ret_secret_ref["name"] | length > 0

  rescue:
    - name: Ensure the error message is set in the resource status
      operator_sdk.util.k8s_status:
        api_version: quay.herve4m.github.io/v1alpha1
        kind: OrganizationPrune
        name: "{{ ansible_operator_meta['name'] }}"
        namespace: "{{ ansible_operator_meta['namespace'] }}"
        status:
          message: "{{ ansible_failed_result['msg'] }}"

    - name: Ensure the error is raised
      ansible.builtin.fail:
        msg: "{{ ansible_failed_result['msg'] }}"

- name: Ensure the error message is cleared from the resource status
  operator_sdk.util.k8s_status:
    api_version: quay.herve4m.github.io/v1alpha1
    kind: OrganizationPrune
    name: "{{ ansible_operator_meta['name'] }}"
    namespace: "{{ ansible_operator_meta['namespace'] }}"
    status:
      message: ""
