---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.quay.herve4m.github.io
spec:
  group: quay.herve4m.github.io
  names:
    kind: Application
    plural: applications
  scope: Namespaced
  versions:
    - name: v1alpha1
      additionalPrinterColumns:
        - name: Quay name
          type: string
          description: Name in Quay
          jsonPath: .spec.name
        - name: Quay organization
          type: string
          description: Organization in Quay
          jsonPath: .spec.organization
        - name: Success
          type: string
          description: The status of the resource creation process in Quay
          jsonPath: .status.conditions[?(@.type == 'Successful')].status
        - name: Message
          type: string
          description: The error message when the resource creation process fails
          jsonPath: .status.message
        - name: State
          type: string
          description: The state of the reconciliation process
          jsonPath: .status.conditions[?(@.type == 'Running')].reason
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          description: Manage Quay Container Registry applications
          properties:
            apiVersion:
              description: >
                APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the
                latest internal value, and may reject unrecognized values.
                More info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: >
                Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint
                the client submits requests to. Cannot be updated. In
                CamelCase. More info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of Application
              type: object
              required:
                - connSecretRef
                - name
                - organization
              properties:
                connSecretRef:
                  description: >
                    Reference to the secret resource that stores the
                    connection parameters to the Quay Container Registry API.

                    The secret must include the 'host', 'token' (or 'username'
                    and 'password'), and optionally the 'validateCerts' keys.
                  properties:
                    name:
                      description: Name of the secret resource.
                      type: string
                    namespace:
                      description: >
                        Namespace of the secret resource. By default, the
                        secret resource is retrieved from the same namespace
                        as the current Application resource.
                      type: string
                  type: object
                  required:
                    - name
                preserveInQuayOnDeletion:
                  default: false
                  description: >
                    Whether to preserve the corresponding Quay object when you
                    delete the Application resource. When set to
                    'false' (the default), the object is deleted from Quay.
                  type: boolean
                retSecretRef:
                  description: >
                    RetSecretRef is the secret resource that the
                    Application resource creates. This secret will
                    store the data that the resource generates:


                    - clientId - ID if the client associated with the application object.

                    - clientSecret - Secret for the client associated with the application object.

                    - name - Application name.

                  properties:
                    name:
                      description: Name of the secret resource.
                      type: string
                    namespace:
                      description: >
                        Namespace of the secret resource. By default, the
                        secret resource is created in the same namespace
                        as the current Application resource.
                      type: string
                  type: object
                  required:
                    - name
                applicationUri:
                  description: URL to the application home page.
                  type: string
                avatarEmail:
                  description: Email address that represents the avatar for the application.
                  format: email
                  type: string
                description:
                  description: Description for the application.
                  type: string
                name:
                  description: Name of the application to create, update, or delete. Application names
                    must be at least two characters long.
                  type: string
                newName:
                  description: New name for the application. Setting this option changes the name
                    of the application which current name is provided in 'name'.
                  type: string
                organization:
                  description: Name of the organization in which to manage the application.
                  type: string
                redirectUri:
                  description: Prefix of the application's OAuth redirection/callback URLs.
                  type: string

            status:
              description: >
                Status defines the observed state of Application
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
