---
apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: redis
      labels:
        app: redis
    stringData:
      database-password: strongpassword
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: redis
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: redis
        spec:
          containers:
            - env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: redis
              image: quay.io/fedora/redis-7:latest
              livenessProbe:
                initialDelaySeconds: 30
                tcpSocket:
                  port: 6379
                timeoutSeconds: 1
              name: redis
              ports:
                - containerPort: 6379
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - test "$(redis-cli -h 127.0.0.1 -a $REDIS_PASSWORD ping)" == "PONG"
                initialDelaySeconds: 5
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 64Mi
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - mountPath: /var/lib/redis/data
                  name: redis-data
          volumes:
            - emptyDir:
                medium: ""
              name: redis-data
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: redis
      name: redis
    spec:
      ports:
        - port: 6379
          protocol: TCP
          targetPort: 6379
      selector:
        app: redis
