---
name: Publish Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/"
      - "mkdocs.yml"

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install required packages
        run: pip install -Iv mkdocs mkdocs-mermaid2-plugin

      - name: Configure Git
        run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Publish documentation
        run: mkdocs gh-deploy --force
...
