---
name: Build and Publish the Operator Manager Container Image

on:
  push:
    branches:
      - main

jobs:
  publish-operator-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the manager container image
        run: make docker-build
        env:
          VERSION: latest

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push the manager container image
        run: make docker-push
        env:
          VERSION: latest
...
