---
name: Build and Publish the Operator Manager Container Image

on:
  push:
    branches:
      - main

jobs:
  publish-operator-image:
    runs-on: ubuntu-latest

    env:
      REGISTRY_URL: quay.io
      ORG: herve4m
      REPO: quay-api-operator

    steps:
      - uses: actions/checkout@v4

      - name: Build the manager container image
        run: make docker-build
        env:
          IMG: ${{ env.REGISTRY_URL }}/${{ env.ORG }}/${{ env.REPO }}:latest

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push the manager container image
        run: make docker-push
        env:
          IMG: ${{ env.REGISTRY_URL }}/${{ env.ORG }}/${{ env.REPO }}:latest
...
